### ISSUE TITLE
滴滴滴

### ISSUE THREAD

**Issue by WarsFeng** [LinuxHub-Group/I-Wanna-Join#37]

**Comment by Arondight** [comment]
@coolrc136 超超，出问题了，Action 的日志里面没响应这个 Issue

**Comment by catusax** [comment]
是github的问题，不是我的问题，我没筛选issue
![图片](https://user-images.githubusercontent.com/11882183/132483023-43d5c48f-8aad-415e-a030-b806c7c22f2d.png)

**Comment by Arondight** [comment]
这位老哥，请再提交一个 Issue
